#ifndef __LWIPOPTS_H__
#define __LWIPOPTS_H__

#define NO_SYS 1
#define LWIP_SOCKET 0
#define LWIP_NETCONN 0

#define LWIP_IPV4 1
#define LWIP_IPV6 0
#define LWIP_UDP 1
#define LWIP_TCP 1
#define LWIP_RAW 1

#define MEM_SIZE (16*1024)
#define MEMP_NUM_PBUF 16
#define MEMP_NUM_UDP_PCB 4
#define MEMP_NUM_TCP_PCB 8
#define MEMP_NUM_TCP_PCB_LISTEN 4

#define PBUF_POOL_SIZE 16
#define PBUF_POOL_BUFSIZE 1280

#define TCP_MSS 536
#define TCP_WND (4 * TCP_MSS)
#define TCP_SND_BUF (4 * TCP_MSS)
#define TCP_SND_QUEUELEN (4 * TCP_SND_BUF / TCP_MSS)
#define TCP_MAXRTX 12
#define TCP_MAXSYNRTX 6

#define DEFAULT_THREAD_STACKSIZE 1024
#define DEFAULT_THREAD_PRIO 1

#define LWIP_STATS 0
#define LWIP_STATS_DISPLAY 0
#define LWIP_DEBUG 0

#endif
#define LWIP_TIMEVAL_PRIVATE 0
